apiVersion: hostedloadbalancer.zonehero.footprintit.net/v1alpha1
kind: HostedLoadBalancer
metadata:
  name: footprint-hlb
  annotations:
    meta.upbound.io/example-id: hlb/v1alpha1/hostedloadbalancer
  labels:
    testing.upbound.io/example-name: example
spec:
  forProvider:
    name: footprint-hlb
    enableHttp2: true
    internal: false
    ec2IamRole: lb-ssm
    ipAddressType: ipv4
    subnets:
    - subnet-0136107242ee6c1aa
    - subnet-0ac022fbb798cdffa
    - subnet-0360ea995b6cce3cf
    securityGroups:
    - sg-0dd1ef1bf1cfb3238
    zoneId: Z00110045FWEPZKVS1M
    zoneName: hlb-eks-dev.orographic.uk
  providerConfigRef:
    name: zonehero-provider-test-partition
