apiVersion: listener.zonehero.footprintit.net/v1alpha1
kind: Listener
metadata:
  name: footprint-hlb-test-listener
spec:
  forProvider:
    loadBalancerRef:
      name: footprint-hlb-test
    port: 80
    protocol: "HTTP"
    targetGroupArn: "arn:aws:elasticloadbalancing:eu-west-1:162646919026:targetgroup/k8s-envoygat-envoyenv-e53adf6655/f1a30a8e2eb0c926" # target group linked to the hlb-test-alb
    overprovisioningFactor: 1.1
  providerConfigRef:
    name: zonehero-provider-test-partition
