apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zonehero-creds-test-partition
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: <NAME_OF_THE_SSM_STORE_IN_YOUR_EKS_CLUSTER> # Replace with the name of your ClusterSecretStore or SecretStore
    kind: SecretStore # Or ClusterSecretStore, depending on your setup
  target:
    name: zonehero-creds-test-partition # This name must match the secretRef in ProviderConfig (e.g. config-test-partition.yaml)
    creationPolicy: Owner
  data:
  - secretKey: credentials
    remoteRef:
      key: /zonehero/test-partition/credentials # Path to the parameter in SSM Parameter Store (should reflect partition)
