apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-ssm-store
  namespace: crossplane-system
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1 # Ensure this matches the region where your SSM Parameter is stored
      # IRSA (IAM Roles for Service Accounts) configuration
      # The ServiceAccount 'external-secrets-sa' must be annotated with the IAM Role ARN
      # e.g. eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/<ROLE_NAME>
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zonehero-creds-test-partition-es
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: zonehero-creds-test-partition # This name must match the secretRef in ProviderConfig (e.g. config-test-partition.yaml)
    creationPolicy: Owner
  data:
  - secretKey: credentials
    remoteRef:
      key: /zonehero/test-partition/credentials # Path to the parameter in SSM Parameter Store (should reflect partition)
