---
apiVersion: v1
kind: Secret
metadata:
  name: zonehero-creds-test-partition
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "api_key": "", # Insert your API key here
      "aws_profile": "", # specify an AWS profile if needed
      "aws_region": "", # specify the AWS region if needed
      "partition": "" # specify the partition if needed (e.g., aws, aws-cn, aws-us-gov)
    }
