apiVersion: zonehero.footprintit.net/v1beta1
kind: ProviderConfig
metadata:
  name: zonehero-provider
spec:
  credentials:
    source: Secret
    secretRef:
      name: zonehero-creds
      namespace: crossplane-system
      key: credentials
