//go:build !ignore_autogenerated

/*
Copyright 2026 The Footprint IT Solutions Authors.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeroNodeGroup) DeepCopyInto(out *HeroNodeGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeroNodeGroup.
func (in *HeroNodeGroup) DeepCopy() *HeroNodeGroup {
	if in == nil {
		return nil
	}
	out := new(HeroNodeGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeroNodeGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeroNodeGroupList) DeepCopyInto(out *HeroNodeGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HeroNodeGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeroNodeGroupList.
func (in *HeroNodeGroupList) DeepCopy() *HeroNodeGroupList {
	if in == nil {
		return nil
	}
	out := new(HeroNodeGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeroNodeGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeroNodeGroupObservation) DeepCopyInto(out *HeroNodeGroupObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeroNodeGroupObservation.
func (in *HeroNodeGroupObservation) DeepCopy() *HeroNodeGroupObservation {
	if in == nil {
		return nil
	}
	out := new(HeroNodeGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeroNodeGroupParameters) DeepCopyInto(out *HeroNodeGroupParameters) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeroNodeGroupParameters.
func (in *HeroNodeGroupParameters) DeepCopy() *HeroNodeGroupParameters {
	if in == nil {
		return nil
	}
	out := new(HeroNodeGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeroNodeGroupSpec) DeepCopyInto(out *HeroNodeGroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeroNodeGroupSpec.
func (in *HeroNodeGroupSpec) DeepCopy() *HeroNodeGroupSpec {
	if in == nil {
		return nil
	}
	out := new(HeroNodeGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeroNodeGroupStatus) DeepCopyInto(out *HeroNodeGroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeroNodeGroupStatus.
func (in *HeroNodeGroupStatus) DeepCopy() *HeroNodeGroupStatus {
	if in == nil {
		return nil
	}
	out := new(HeroNodeGroupStatus)
	in.DeepCopyInto(out)
	return out
}
