name: OrographicLift/hlb
resources:
    confluent_ksql_cluster Resource - terraform-provider-confluent:
        subCategory: ""
        name: confluent_ksql_cluster Resource - terraform-provider-confluent
        title: confluent_ksql_cluster Resource - terraform-provider-confluent
        argumentDocs:
            docs/index.md: )
            docs/resources/*.md: )
        importStatements: []
