//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HLBListenerAttachment) DeepCopyInto(out *HLBListenerAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HLBListenerAttachment.
func (in *HLBListenerAttachment) DeepCopy() *HLBListenerAttachment {
	if in == nil {
		return nil
	}
	out := new(HLBListenerAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HLBListenerAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HLBListenerAttachmentInitParameters) DeepCopyInto(out *HLBListenerAttachmentInitParameters) {
	*out = *in
	if in.AlpnPolicy != nil {
		in, out := &in.AlpnPolicy, &out.AlpnPolicy
		*out = new(string)
		**out = **in
	}
	if in.CertificateSecretsName != nil {
		in, out := &in.CertificateSecretsName, &out.CertificateSecretsName
		*out = new(string)
		**out = **in
	}
	if in.EnableDeletionProtection != nil {
		in, out := &in.EnableDeletionProtection, &out.EnableDeletionProtection
		*out = new(bool)
		**out = **in
	}
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.OverprovisioningFactor != nil {
		in, out := &in.OverprovisioningFactor, &out.OverprovisioningFactor
		*out = new(float64)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.TargetGroupArn != nil {
		in, out := &in.TargetGroupArn, &out.TargetGroupArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HLBListenerAttachmentInitParameters.
func (in *HLBListenerAttachmentInitParameters) DeepCopy() *HLBListenerAttachmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(HLBListenerAttachmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HLBListenerAttachmentList) DeepCopyInto(out *HLBListenerAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HLBListenerAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HLBListenerAttachmentList.
func (in *HLBListenerAttachmentList) DeepCopy() *HLBListenerAttachmentList {
	if in == nil {
		return nil
	}
	out := new(HLBListenerAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HLBListenerAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HLBListenerAttachmentObservation) DeepCopyInto(out *HLBListenerAttachmentObservation) {
	*out = *in
	if in.AlpnPolicy != nil {
		in, out := &in.AlpnPolicy, &out.AlpnPolicy
		*out = new(string)
		**out = **in
	}
	if in.CertificateSecretsName != nil {
		in, out := &in.CertificateSecretsName, &out.CertificateSecretsName
		*out = new(string)
		**out = **in
	}
	if in.EnableDeletionProtection != nil {
		in, out := &in.EnableDeletionProtection, &out.EnableDeletionProtection
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.OverprovisioningFactor != nil {
		in, out := &in.OverprovisioningFactor, &out.OverprovisioningFactor
		*out = new(float64)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.TargetGroupArn != nil {
		in, out := &in.TargetGroupArn, &out.TargetGroupArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HLBListenerAttachmentObservation.
func (in *HLBListenerAttachmentObservation) DeepCopy() *HLBListenerAttachmentObservation {
	if in == nil {
		return nil
	}
	out := new(HLBListenerAttachmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HLBListenerAttachmentParameters) DeepCopyInto(out *HLBListenerAttachmentParameters) {
	*out = *in
	if in.AlpnPolicy != nil {
		in, out := &in.AlpnPolicy, &out.AlpnPolicy
		*out = new(string)
		**out = **in
	}
	if in.CertificateSecretsName != nil {
		in, out := &in.CertificateSecretsName, &out.CertificateSecretsName
		*out = new(string)
		**out = **in
	}
	if in.EnableDeletionProtection != nil {
		in, out := &in.EnableDeletionProtection, &out.EnableDeletionProtection
		*out = new(bool)
		**out = **in
	}
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.OverprovisioningFactor != nil {
		in, out := &in.OverprovisioningFactor, &out.OverprovisioningFactor
		*out = new(float64)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.TargetGroupArn != nil {
		in, out := &in.TargetGroupArn, &out.TargetGroupArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HLBListenerAttachmentParameters.
func (in *HLBListenerAttachmentParameters) DeepCopy() *HLBListenerAttachmentParameters {
	if in == nil {
		return nil
	}
	out := new(HLBListenerAttachmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HLBListenerAttachmentSpec) DeepCopyInto(out *HLBListenerAttachmentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HLBListenerAttachmentSpec.
func (in *HLBListenerAttachmentSpec) DeepCopy() *HLBListenerAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(HLBListenerAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HLBListenerAttachmentStatus) DeepCopyInto(out *HLBListenerAttachmentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HLBListenerAttachmentStatus.
func (in *HLBListenerAttachmentStatus) DeepCopy() *HLBListenerAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(HLBListenerAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedLoadBalancer) DeepCopyInto(out *HostedLoadBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedLoadBalancer.
func (in *HostedLoadBalancer) DeepCopy() *HostedLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(HostedLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostedLoadBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedLoadBalancerInitParameters) DeepCopyInto(out *HostedLoadBalancerInitParameters) {
	*out = *in
	if in.ClientKeepAlive != nil {
		in, out := &in.ClientKeepAlive, &out.ClientKeepAlive
		*out = new(float64)
		**out = **in
	}
	if in.ConnectionDrainingTimeout != nil {
		in, out := &in.ConnectionDrainingTimeout, &out.ConnectionDrainingTimeout
		*out = new(float64)
		**out = **in
	}
	if in.EC2IAMRole != nil {
		in, out := &in.EC2IAMRole, &out.EC2IAMRole
		*out = new(string)
		**out = **in
	}
	if in.EnableCrossZoneLoadBalancing != nil {
		in, out := &in.EnableCrossZoneLoadBalancing, &out.EnableCrossZoneLoadBalancing
		*out = new(string)
		**out = **in
	}
	if in.EnableDeletionProtection != nil {
		in, out := &in.EnableDeletionProtection, &out.EnableDeletionProtection
		*out = new(bool)
		**out = **in
	}
	if in.EnableHttp2 != nil {
		in, out := &in.EnableHttp2, &out.EnableHttp2
		*out = new(bool)
		**out = **in
	}
	if in.IPAddressType != nil {
		in, out := &in.IPAddressType, &out.IPAddressType
		*out = new(string)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(float64)
		**out = **in
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(bool)
		**out = **in
	}
	if in.PreferredMaintenanceWindow != nil {
		in, out := &in.PreferredMaintenanceWindow, &out.PreferredMaintenanceWindow
		*out = new(string)
		**out = **in
	}
	if in.PreserveHostHeader != nil {
		in, out := &in.PreserveHostHeader, &out.PreserveHostHeader
		*out = new(bool)
		**out = **in
	}
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.XffHeaderProcessingMode != nil {
		in, out := &in.XffHeaderProcessingMode, &out.XffHeaderProcessingMode
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneName != nil {
		in, out := &in.ZoneName, &out.ZoneName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedLoadBalancerInitParameters.
func (in *HostedLoadBalancerInitParameters) DeepCopy() *HostedLoadBalancerInitParameters {
	if in == nil {
		return nil
	}
	out := new(HostedLoadBalancerInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedLoadBalancerList) DeepCopyInto(out *HostedLoadBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HostedLoadBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedLoadBalancerList.
func (in *HostedLoadBalancerList) DeepCopy() *HostedLoadBalancerList {
	if in == nil {
		return nil
	}
	out := new(HostedLoadBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostedLoadBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedLoadBalancerObservation) DeepCopyInto(out *HostedLoadBalancerObservation) {
	*out = *in
	if in.ClientKeepAlive != nil {
		in, out := &in.ClientKeepAlive, &out.ClientKeepAlive
		*out = new(float64)
		**out = **in
	}
	if in.ConnectionDrainingTimeout != nil {
		in, out := &in.ConnectionDrainingTimeout, &out.ConnectionDrainingTimeout
		*out = new(float64)
		**out = **in
	}
	if in.DNSName != nil {
		in, out := &in.DNSName, &out.DNSName
		*out = new(string)
		**out = **in
	}
	if in.EC2IAMRole != nil {
		in, out := &in.EC2IAMRole, &out.EC2IAMRole
		*out = new(string)
		**out = **in
	}
	if in.EnableCrossZoneLoadBalancing != nil {
		in, out := &in.EnableCrossZoneLoadBalancing, &out.EnableCrossZoneLoadBalancing
		*out = new(string)
		**out = **in
	}
	if in.EnableDeletionProtection != nil {
		in, out := &in.EnableDeletionProtection, &out.EnableDeletionProtection
		*out = new(bool)
		**out = **in
	}
	if in.EnableHttp2 != nil {
		in, out := &in.EnableHttp2, &out.EnableHttp2
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IPAddressType != nil {
		in, out := &in.IPAddressType, &out.IPAddressType
		*out = new(string)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(float64)
		**out = **in
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(bool)
		**out = **in
	}
	if in.PreferredMaintenanceWindow != nil {
		in, out := &in.PreferredMaintenanceWindow, &out.PreferredMaintenanceWindow
		*out = new(string)
		**out = **in
	}
	if in.PreserveHostHeader != nil {
		in, out := &in.PreserveHostHeader, &out.PreserveHostHeader
		*out = new(bool)
		**out = **in
	}
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.XffHeaderProcessingMode != nil {
		in, out := &in.XffHeaderProcessingMode, &out.XffHeaderProcessingMode
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneName != nil {
		in, out := &in.ZoneName, &out.ZoneName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedLoadBalancerObservation.
func (in *HostedLoadBalancerObservation) DeepCopy() *HostedLoadBalancerObservation {
	if in == nil {
		return nil
	}
	out := new(HostedLoadBalancerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedLoadBalancerParameters) DeepCopyInto(out *HostedLoadBalancerParameters) {
	*out = *in
	if in.ClientKeepAlive != nil {
		in, out := &in.ClientKeepAlive, &out.ClientKeepAlive
		*out = new(float64)
		**out = **in
	}
	if in.ConnectionDrainingTimeout != nil {
		in, out := &in.ConnectionDrainingTimeout, &out.ConnectionDrainingTimeout
		*out = new(float64)
		**out = **in
	}
	if in.EC2IAMRole != nil {
		in, out := &in.EC2IAMRole, &out.EC2IAMRole
		*out = new(string)
		**out = **in
	}
	if in.EnableCrossZoneLoadBalancing != nil {
		in, out := &in.EnableCrossZoneLoadBalancing, &out.EnableCrossZoneLoadBalancing
		*out = new(string)
		**out = **in
	}
	if in.EnableDeletionProtection != nil {
		in, out := &in.EnableDeletionProtection, &out.EnableDeletionProtection
		*out = new(bool)
		**out = **in
	}
	if in.EnableHttp2 != nil {
		in, out := &in.EnableHttp2, &out.EnableHttp2
		*out = new(bool)
		**out = **in
	}
	if in.IPAddressType != nil {
		in, out := &in.IPAddressType, &out.IPAddressType
		*out = new(string)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(float64)
		**out = **in
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(bool)
		**out = **in
	}
	if in.PreferredMaintenanceWindow != nil {
		in, out := &in.PreferredMaintenanceWindow, &out.PreferredMaintenanceWindow
		*out = new(string)
		**out = **in
	}
	if in.PreserveHostHeader != nil {
		in, out := &in.PreserveHostHeader, &out.PreserveHostHeader
		*out = new(bool)
		**out = **in
	}
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.XffHeaderProcessingMode != nil {
		in, out := &in.XffHeaderProcessingMode, &out.XffHeaderProcessingMode
		*out = new(string)
		**out = **in
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
	if in.ZoneName != nil {
		in, out := &in.ZoneName, &out.ZoneName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedLoadBalancerParameters.
func (in *HostedLoadBalancerParameters) DeepCopy() *HostedLoadBalancerParameters {
	if in == nil {
		return nil
	}
	out := new(HostedLoadBalancerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedLoadBalancerSpec) DeepCopyInto(out *HostedLoadBalancerSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedLoadBalancerSpec.
func (in *HostedLoadBalancerSpec) DeepCopy() *HostedLoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(HostedLoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostedLoadBalancerStatus) DeepCopyInto(out *HostedLoadBalancerStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostedLoadBalancerStatus.
func (in *HostedLoadBalancerStatus) DeepCopy() *HostedLoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(HostedLoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}
