// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type HostedLoadBalancerInitParameters struct {

	// 604800 seconds, default 3600). This setting determines how long the load balancer maintains idle keepalive connections with clients. Longer values can improve performance by reducing connection establishment overhead, but consume more resources.
	// The time in seconds to keep client connections alive (60-604800 seconds, default 3600). This setting determines how long the load balancer maintains idle keepalive connections with clients. Longer values can improve performance by reducing connection establishment overhead, but consume more resources.
	ClientKeepAlive *float64 `json:"clientKeepAlive,omitempty" tf:"client_keep_alive,omitempty"`

	// in event occurs, load balancer nodes are taken out of the DNS record immediately but we wait for connection_draining_timeout minutes before terminating the instances. This is most useful with HTTP clients that do not respect DNS TLL.
	// When a scale-in event occurs, load balancer nodes are taken out of the DNS record immediately but we wait for `connection_draining_timeout` minutes before terminating the instances. This is most useful with HTTP clients that do not respect DNS TLL.
	ConnectionDrainingTimeout *float64 `json:"connectionDrainingTimeout,omitempty" tf:"connection_draining_timeout,omitempty"`

	// (String) Allows the user to assign a role permitting root access to proxy instances via AWS SSM. It is stronly discouraged to change this value as this compromises security on many levels. Use only to perfom audits. Valid values are:
	// Allows the user to assign a role permitting root access to proxy instances via AWS SSM. It is *stronly discouraged* to change this value as this compromises security on many levels. Use only to perfom audits. Valid values are:
	// * `lb-standard` (default)
	// * `lb-ssm`
	// The role will only be applied to newly created proxy instances, you must trigger an Autoscaling Group Instance Refresh manually for this change to take effect immediately.
	EC2IAMRole *string `json:"ec2IamRole,omitempty" tf:"ec2_iam_role,omitempty"`

	// (String) Configures how the load balancer distributes traffic between Availability Zones. Valid values:
	// Configures how the load balancer distributes traffic between Availability Zones. Valid values:
	//
	// * `full` - Distributes traffic evenly across all instances in all zones
	// * `avoid` (default) - Attempts to distribute traffic within a zone first, only sending cross-zone traffic when necessary
	// * `off` - Keeps traffic within the same zone
	//
	// The `avoid` mode helps optimize for both availability and performance while minimizing cross-AZ data transfer costs.
	EnableCrossZoneLoadBalancing *string `json:"enableCrossZoneLoadBalancing,omitempty" tf:"enable_cross_zone_load_balancing,omitempty"`

	// (Boolean) If true, deletion of the load balancer will be disabled via the API. This prevents accidental deletion of production load balancers. You must set this to false and apply the change before you can delete the load balancer.
	// If true, deletion of the load balancer will be disabled via the API. This prevents accidental deletion of production load balancers. You must set this to false and apply the change before you can delete the load balancer.
	EnableDeletionProtection *bool `json:"enableDeletionProtection,omitempty" tf:"enable_deletion_protection,omitempty"`

	// (Boolean) Indicates whether HTTP/2 is enabled. HTTP/2 provides improved performance through features like multiplexing, header compression, and server push. Enabled by default. Only disable this if you have specific compatibility requirements with HTTP/1.x.
	// Indicates whether HTTP/2 is enabled. HTTP/2 provides improved performance through features like multiplexing, header compression, and server push. Enabled by default. Only disable this if you have specific compatibility requirements with HTTP/1.x.
	EnableHttp2 *bool `json:"enableHttp2,omitempty" tf:"enable_http2,omitempty"`

	// (String) The type of IP addresses used by the subnets for your load balancer. Valid values:
	// The type of IP addresses used by the subnets for your load balancer. Valid values:
	//
	// * `ipv4` (default) - The load balancer has IPv4 addresses only
	// * `dualstack` - The load balancer has both IPv4 and IPv6 addresses
	// * `dualstack-without-public-ipv4` - The load balancer has IPv6 addresses and private IPv4 addresses
	//
	// Choose based on your application's networking requirements and client compatibility needs.
	IPAddressType *string `json:"ipAddressType,omitempty" tf:"ip_address_type,omitempty"`

	// 4000 seconds. Default is 60 seconds. Increase this if your application requires longer-lived idle connections.
	// The time in seconds that a connection is allowed to be idle (no data transfer) before it is closed by the load balancer. Valid values are 1-4000 seconds. Default is 60 seconds. Increase this if your application requires longer-lived idle connections.
	IdleTimeout *float64 `json:"idleTimeout,omitempty" tf:"idle_timeout,omitempty"`

	// (Boolean) If true, the load balancer will be internal (private). Internal load balancers route traffic within your VPC and are not accessible from the internet. Use this for internal services or when you want to restrict access to your VPC. This cannot be changed after creation.
	// If true, the load balancer will be internal (private). Internal load balancers route traffic within your VPC and are not accessible from the internet. Use this for internal services or when you want to restrict access to your VPC. This cannot be changed after creation.
	Internal *bool `json:"internal,omitempty" tf:"internal,omitempty"`

	// (String) The name of the load balancer. Must be unique within your account, max 32 characters, alphanumeric and hyphens only. This name will be used in DNS records and AWS resource names, so choose something meaningful and compliant with DNS naming conventions.
	// The name of the load balancer. Must be unique within your account, max 32 characters, alphanumeric and hyphens only. This name will be used in DNS records and AWS resource names, so choose something meaningful and compliant with DNS naming conventions.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// 6 characters long. Conflicts with the name attribute - you can only use one or the other.
	// Creates a unique name beginning with the specified prefix. The prefix must be 1-6 characters long. Conflicts with the `name` attribute - you can only use one or the other.
	NamePrefix *string `json:"namePrefix,omitempty" tf:"name_prefix,omitempty"`

	// ddd,hh24:mm-hh24:mm where:
	// Specifies a time window during which load balancer node forced replacement should preferably occur. An empty string is a valid value. The format is `ddd-ddd,hh24:mm-hh24:mm` where:
	//
	// * `ddd-ddd` represents a day range (e.g., `mon-fri` for Monday to Friday)
	// * `hh24:mm-hh24:mm` represents a time range in 24-hour format in UTC (e.g., `01:00-03:00` for 1 AM to 3 AM UTC)
	//
	// **Important:** All times are in UTC. The day of the week refers to the start time of the window. For time ranges that cross midnight, the window will finish on the next day.
	//
	// Examples:
	// * `mon-wed,02:00-04:00` - Monday through Wednesday, between 2 AM and 4 AM UTC
	// * `mon-fri,23:00-02:00` - Monday through Friday, starting at 11 PM UTC each day and ending at 2 AM UTC the following day. The last window starts at 11 PM UTC Friday and ends at 2 AM UTC Saturday
	//
	// When updates to the load balancer nodes are available, newly started instances always use the newest version, and older versions are progressively phased out as scale-in events occur. Additionally, any remaining instances running out-of-date versions will be automatically replaced during the specified maintenance window.
	//
	// Valid values for days are:
	//
	// * `mon` - Monday
	// * `tue` - Tuesday
	// * `wed` - Wednesday
	// * `thu` - Thursday
	// * `fri` - Friday
	// * `sat` - Saturday
	// * `sun` - Sunday
	//
	// **Note:** Urgent updates may be applied outside of the preferred maintenance window and without notice. `connection_draining_timeout` is always respected.
	//
	// If unspecified, non-urgent forced replacements will occur at night in the region.
	PreferredMaintenanceWindow *string `json:"preferredMaintenanceWindow,omitempty" tf:"preferred_maintenance_window,omitempty"`

	// (Boolean) If true, the load balancer preserves the original Host header value in requests forwarded to targets. This is useful when your backend application needs to know the original hostname requested by the client, for example with virtual hosting or when generating absolute URLs.
	// If true, the load balancer preserves the original Host header value in requests forwarded to targets. This is useful when your backend application needs to know the original hostname requested by the client, for example with virtual hosting or when generating absolute URLs.
	PreserveHostHeader *bool `json:"preserveHostHeader,omitempty" tf:"preserve_host_header,omitempty"`

	// (Set of String) List of security group IDs to assign to the load balancer. The security groups must allow inbound traffic on the listener ports and health check ports. They should also allow outbound traffic to your target instances or IP addresses, and the HLB control plane.
	// List of security group IDs to assign to the load balancer. The security groups must allow inbound traffic on the listener ports and health check ports. They should also allow outbound traffic to your target instances or IP addresses, and the HLB control plane.
	// +listType=set
	SecurityGroups []*string `json:"securityGroups,omitempty" tf:"security_groups,omitempty"`

	// facing load balancers, these must be public subnets.
	// List of subnet IDs to attach to the load balancer. The subnets must be in at least two different Availability Zones for high availability. For internal load balancers, these must be private subnets. For internet-facing load balancers, these must be public subnets.
	// +listType=set
	Subnets []*string `json:"subnets,omitempty" tf:"subnets,omitempty"`

	// value pairs that help you organize and categorize your resources. Common uses include:
	// A map of tags to assign to the load balancer and related resources. Tags are key-value pairs that help you organize and categorize your resources. Common uses include:
	//
	// * Environment identification (e.g., `environment = "production"`)
	// * Cost allocation (e.g., `project = "mobile-app"`)
	// * Security/compliance labeling
	// * Automation and operations management
	// A maximum of 5 tags can be assigned (AWS Marketplace limitation).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Forwarded-For header. Valid values:
	// Controls how the load balancer handles the X-Forwarded-For header. Valid values:
	//
	// * `append` (default) - Appends the client IP to any existing X-Forwarded-For header
	// * `preserve` - Keeps the original X-Forwarded-For header unchanged
	// * `remove` - Removes any existing X-Forwarded-For header
	//
	// This header is important for identifying the original client IP address when requests pass through the load balancer.
	XffHeaderProcessingMode *string `json:"xffHeaderProcessingMode,omitempty" tf:"xff_header_processing_mode,omitempty"`

	// (String) The ID of the zone
	// The ID of the zone
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// (String) The name of the zone
	// The name of the zone
	ZoneName *string `json:"zoneName,omitempty" tf:"zone_name,omitempty"`
}

type HostedLoadBalancerObservation struct {

	// 604800 seconds, default 3600). This setting determines how long the load balancer maintains idle keepalive connections with clients. Longer values can improve performance by reducing connection establishment overhead, but consume more resources.
	// The time in seconds to keep client connections alive (60-604800 seconds, default 3600). This setting determines how long the load balancer maintains idle keepalive connections with clients. Longer values can improve performance by reducing connection establishment overhead, but consume more resources.
	ClientKeepAlive *float64 `json:"clientKeepAlive,omitempty" tf:"client_keep_alive,omitempty"`

	// in event occurs, load balancer nodes are taken out of the DNS record immediately but we wait for connection_draining_timeout minutes before terminating the instances. This is most useful with HTTP clients that do not respect DNS TLL.
	// When a scale-in event occurs, load balancer nodes are taken out of the DNS record immediately but we wait for `connection_draining_timeout` minutes before terminating the instances. This is most useful with HTTP clients that do not respect DNS TLL.
	ConnectionDrainingTimeout *float64 `json:"connectionDrainingTimeout,omitempty" tf:"connection_draining_timeout,omitempty"`

	// (String) The DNS name of the load balancer
	// The DNS name of the load balancer
	DNSName *string `json:"dnsName,omitempty" tf:"dns_name,omitempty"`

	// (String) Allows the user to assign a role permitting root access to proxy instances via AWS SSM. It is stronly discouraged to change this value as this compromises security on many levels. Use only to perfom audits. Valid values are:
	// Allows the user to assign a role permitting root access to proxy instances via AWS SSM. It is *stronly discouraged* to change this value as this compromises security on many levels. Use only to perfom audits. Valid values are:
	// * `lb-standard` (default)
	// * `lb-ssm`
	// The role will only be applied to newly created proxy instances, you must trigger an Autoscaling Group Instance Refresh manually for this change to take effect immediately.
	EC2IAMRole *string `json:"ec2IamRole,omitempty" tf:"ec2_iam_role,omitempty"`

	// (String) Configures how the load balancer distributes traffic between Availability Zones. Valid values:
	// Configures how the load balancer distributes traffic between Availability Zones. Valid values:
	//
	// * `full` - Distributes traffic evenly across all instances in all zones
	// * `avoid` (default) - Attempts to distribute traffic within a zone first, only sending cross-zone traffic when necessary
	// * `off` - Keeps traffic within the same zone
	//
	// The `avoid` mode helps optimize for both availability and performance while minimizing cross-AZ data transfer costs.
	EnableCrossZoneLoadBalancing *string `json:"enableCrossZoneLoadBalancing,omitempty" tf:"enable_cross_zone_load_balancing,omitempty"`

	// (Boolean) If true, deletion of the load balancer will be disabled via the API. This prevents accidental deletion of production load balancers. You must set this to false and apply the change before you can delete the load balancer.
	// If true, deletion of the load balancer will be disabled via the API. This prevents accidental deletion of production load balancers. You must set this to false and apply the change before you can delete the load balancer.
	EnableDeletionProtection *bool `json:"enableDeletionProtection,omitempty" tf:"enable_deletion_protection,omitempty"`

	// (Boolean) Indicates whether HTTP/2 is enabled. HTTP/2 provides improved performance through features like multiplexing, header compression, and server push. Enabled by default. Only disable this if you have specific compatibility requirements with HTTP/1.x.
	// Indicates whether HTTP/2 is enabled. HTTP/2 provides improved performance through features like multiplexing, header compression, and server push. Enabled by default. Only disable this if you have specific compatibility requirements with HTTP/1.x.
	EnableHttp2 *bool `json:"enableHttp2,omitempty" tf:"enable_http2,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The type of IP addresses used by the subnets for your load balancer. Valid values:
	// The type of IP addresses used by the subnets for your load balancer. Valid values:
	//
	// * `ipv4` (default) - The load balancer has IPv4 addresses only
	// * `dualstack` - The load balancer has both IPv4 and IPv6 addresses
	// * `dualstack-without-public-ipv4` - The load balancer has IPv6 addresses and private IPv4 addresses
	//
	// Choose based on your application's networking requirements and client compatibility needs.
	IPAddressType *string `json:"ipAddressType,omitempty" tf:"ip_address_type,omitempty"`

	// 4000 seconds. Default is 60 seconds. Increase this if your application requires longer-lived idle connections.
	// The time in seconds that a connection is allowed to be idle (no data transfer) before it is closed by the load balancer. Valid values are 1-4000 seconds. Default is 60 seconds. Increase this if your application requires longer-lived idle connections.
	IdleTimeout *float64 `json:"idleTimeout,omitempty" tf:"idle_timeout,omitempty"`

	// (Boolean) If true, the load balancer will be internal (private). Internal load balancers route traffic within your VPC and are not accessible from the internet. Use this for internal services or when you want to restrict access to your VPC. This cannot be changed after creation.
	// If true, the load balancer will be internal (private). Internal load balancers route traffic within your VPC and are not accessible from the internet. Use this for internal services or when you want to restrict access to your VPC. This cannot be changed after creation.
	Internal *bool `json:"internal,omitempty" tf:"internal,omitempty"`

	// (String) The name of the load balancer. Must be unique within your account, max 32 characters, alphanumeric and hyphens only. This name will be used in DNS records and AWS resource names, so choose something meaningful and compliant with DNS naming conventions.
	// The name of the load balancer. Must be unique within your account, max 32 characters, alphanumeric and hyphens only. This name will be used in DNS records and AWS resource names, so choose something meaningful and compliant with DNS naming conventions.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// 6 characters long. Conflicts with the name attribute - you can only use one or the other.
	// Creates a unique name beginning with the specified prefix. The prefix must be 1-6 characters long. Conflicts with the `name` attribute - you can only use one or the other.
	NamePrefix *string `json:"namePrefix,omitempty" tf:"name_prefix,omitempty"`

	// ddd,hh24:mm-hh24:mm where:
	// Specifies a time window during which load balancer node forced replacement should preferably occur. An empty string is a valid value. The format is `ddd-ddd,hh24:mm-hh24:mm` where:
	//
	// * `ddd-ddd` represents a day range (e.g., `mon-fri` for Monday to Friday)
	// * `hh24:mm-hh24:mm` represents a time range in 24-hour format in UTC (e.g., `01:00-03:00` for 1 AM to 3 AM UTC)
	//
	// **Important:** All times are in UTC. The day of the week refers to the start time of the window. For time ranges that cross midnight, the window will finish on the next day.
	//
	// Examples:
	// * `mon-wed,02:00-04:00` - Monday through Wednesday, between 2 AM and 4 AM UTC
	// * `mon-fri,23:00-02:00` - Monday through Friday, starting at 11 PM UTC each day and ending at 2 AM UTC the following day. The last window starts at 11 PM UTC Friday and ends at 2 AM UTC Saturday
	//
	// When updates to the load balancer nodes are available, newly started instances always use the newest version, and older versions are progressively phased out as scale-in events occur. Additionally, any remaining instances running out-of-date versions will be automatically replaced during the specified maintenance window.
	//
	// Valid values for days are:
	//
	// * `mon` - Monday
	// * `tue` - Tuesday
	// * `wed` - Wednesday
	// * `thu` - Thursday
	// * `fri` - Friday
	// * `sat` - Saturday
	// * `sun` - Sunday
	//
	// **Note:** Urgent updates may be applied outside of the preferred maintenance window and without notice. `connection_draining_timeout` is always respected.
	//
	// If unspecified, non-urgent forced replacements will occur at night in the region.
	PreferredMaintenanceWindow *string `json:"preferredMaintenanceWindow,omitempty" tf:"preferred_maintenance_window,omitempty"`

	// (Boolean) If true, the load balancer preserves the original Host header value in requests forwarded to targets. This is useful when your backend application needs to know the original hostname requested by the client, for example with virtual hosting or when generating absolute URLs.
	// If true, the load balancer preserves the original Host header value in requests forwarded to targets. This is useful when your backend application needs to know the original hostname requested by the client, for example with virtual hosting or when generating absolute URLs.
	PreserveHostHeader *bool `json:"preserveHostHeader,omitempty" tf:"preserve_host_header,omitempty"`

	// (Set of String) List of security group IDs to assign to the load balancer. The security groups must allow inbound traffic on the listener ports and health check ports. They should also allow outbound traffic to your target instances or IP addresses, and the HLB control plane.
	// List of security group IDs to assign to the load balancer. The security groups must allow inbound traffic on the listener ports and health check ports. They should also allow outbound traffic to your target instances or IP addresses, and the HLB control plane.
	// +listType=set
	SecurityGroups []*string `json:"securityGroups,omitempty" tf:"security_groups,omitempty"`

	// (String) The state of the load balancer
	// The state of the load balancer
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// facing load balancers, these must be public subnets.
	// List of subnet IDs to attach to the load balancer. The subnets must be in at least two different Availability Zones for high availability. For internal load balancers, these must be private subnets. For internet-facing load balancers, these must be public subnets.
	// +listType=set
	Subnets []*string `json:"subnets,omitempty" tf:"subnets,omitempty"`

	// value pairs that help you organize and categorize your resources. Common uses include:
	// A map of tags to assign to the load balancer and related resources. Tags are key-value pairs that help you organize and categorize your resources. Common uses include:
	//
	// * Environment identification (e.g., `environment = "production"`)
	// * Cost allocation (e.g., `project = "mobile-app"`)
	// * Security/compliance labeling
	// * Automation and operations management
	// A maximum of 5 tags can be assigned (AWS Marketplace limitation).
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Forwarded-For header. Valid values:
	// Controls how the load balancer handles the X-Forwarded-For header. Valid values:
	//
	// * `append` (default) - Appends the client IP to any existing X-Forwarded-For header
	// * `preserve` - Keeps the original X-Forwarded-For header unchanged
	// * `remove` - Removes any existing X-Forwarded-For header
	//
	// This header is important for identifying the original client IP address when requests pass through the load balancer.
	XffHeaderProcessingMode *string `json:"xffHeaderProcessingMode,omitempty" tf:"xff_header_processing_mode,omitempty"`

	// (String) The ID of the zone
	// The ID of the zone
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// (String) The name of the zone
	// The name of the zone
	ZoneName *string `json:"zoneName,omitempty" tf:"zone_name,omitempty"`
}

type HostedLoadBalancerParameters struct {

	// 604800 seconds, default 3600). This setting determines how long the load balancer maintains idle keepalive connections with clients. Longer values can improve performance by reducing connection establishment overhead, but consume more resources.
	// The time in seconds to keep client connections alive (60-604800 seconds, default 3600). This setting determines how long the load balancer maintains idle keepalive connections with clients. Longer values can improve performance by reducing connection establishment overhead, but consume more resources.
	// +kubebuilder:validation:Optional
	ClientKeepAlive *float64 `json:"clientKeepAlive,omitempty" tf:"client_keep_alive,omitempty"`

	// in event occurs, load balancer nodes are taken out of the DNS record immediately but we wait for connection_draining_timeout minutes before terminating the instances. This is most useful with HTTP clients that do not respect DNS TLL.
	// When a scale-in event occurs, load balancer nodes are taken out of the DNS record immediately but we wait for `connection_draining_timeout` minutes before terminating the instances. This is most useful with HTTP clients that do not respect DNS TLL.
	// +kubebuilder:validation:Optional
	ConnectionDrainingTimeout *float64 `json:"connectionDrainingTimeout,omitempty" tf:"connection_draining_timeout,omitempty"`

	// (String) Allows the user to assign a role permitting root access to proxy instances via AWS SSM. It is stronly discouraged to change this value as this compromises security on many levels. Use only to perfom audits. Valid values are:
	// Allows the user to assign a role permitting root access to proxy instances via AWS SSM. It is *stronly discouraged* to change this value as this compromises security on many levels. Use only to perfom audits. Valid values are:
	// * `lb-standard` (default)
	// * `lb-ssm`
	// The role will only be applied to newly created proxy instances, you must trigger an Autoscaling Group Instance Refresh manually for this change to take effect immediately.
	// +kubebuilder:validation:Optional
	EC2IAMRole *string `json:"ec2IamRole,omitempty" tf:"ec2_iam_role,omitempty"`

	// (String) Configures how the load balancer distributes traffic between Availability Zones. Valid values:
	// Configures how the load balancer distributes traffic between Availability Zones. Valid values:
	//
	// * `full` - Distributes traffic evenly across all instances in all zones
	// * `avoid` (default) - Attempts to distribute traffic within a zone first, only sending cross-zone traffic when necessary
	// * `off` - Keeps traffic within the same zone
	//
	// The `avoid` mode helps optimize for both availability and performance while minimizing cross-AZ data transfer costs.
	// +kubebuilder:validation:Optional
	EnableCrossZoneLoadBalancing *string `json:"enableCrossZoneLoadBalancing,omitempty" tf:"enable_cross_zone_load_balancing,omitempty"`

	// (Boolean) If true, deletion of the load balancer will be disabled via the API. This prevents accidental deletion of production load balancers. You must set this to false and apply the change before you can delete the load balancer.
	// If true, deletion of the load balancer will be disabled via the API. This prevents accidental deletion of production load balancers. You must set this to false and apply the change before you can delete the load balancer.
	// +kubebuilder:validation:Optional
	EnableDeletionProtection *bool `json:"enableDeletionProtection,omitempty" tf:"enable_deletion_protection,omitempty"`

	// (Boolean) Indicates whether HTTP/2 is enabled. HTTP/2 provides improved performance through features like multiplexing, header compression, and server push. Enabled by default. Only disable this if you have specific compatibility requirements with HTTP/1.x.
	// Indicates whether HTTP/2 is enabled. HTTP/2 provides improved performance through features like multiplexing, header compression, and server push. Enabled by default. Only disable this if you have specific compatibility requirements with HTTP/1.x.
	// +kubebuilder:validation:Optional
	EnableHttp2 *bool `json:"enableHttp2,omitempty" tf:"enable_http2,omitempty"`

	// (String) The type of IP addresses used by the subnets for your load balancer. Valid values:
	// The type of IP addresses used by the subnets for your load balancer. Valid values:
	//
	// * `ipv4` (default) - The load balancer has IPv4 addresses only
	// * `dualstack` - The load balancer has both IPv4 and IPv6 addresses
	// * `dualstack-without-public-ipv4` - The load balancer has IPv6 addresses and private IPv4 addresses
	//
	// Choose based on your application's networking requirements and client compatibility needs.
	// +kubebuilder:validation:Optional
	IPAddressType *string `json:"ipAddressType,omitempty" tf:"ip_address_type,omitempty"`

	// 4000 seconds. Default is 60 seconds. Increase this if your application requires longer-lived idle connections.
	// The time in seconds that a connection is allowed to be idle (no data transfer) before it is closed by the load balancer. Valid values are 1-4000 seconds. Default is 60 seconds. Increase this if your application requires longer-lived idle connections.
	// +kubebuilder:validation:Optional
	IdleTimeout *float64 `json:"idleTimeout,omitempty" tf:"idle_timeout,omitempty"`

	// (Boolean) If true, the load balancer will be internal (private). Internal load balancers route traffic within your VPC and are not accessible from the internet. Use this for internal services or when you want to restrict access to your VPC. This cannot be changed after creation.
	// If true, the load balancer will be internal (private). Internal load balancers route traffic within your VPC and are not accessible from the internet. Use this for internal services or when you want to restrict access to your VPC. This cannot be changed after creation.
	// +kubebuilder:validation:Optional
	Internal *bool `json:"internal,omitempty" tf:"internal,omitempty"`

	// (String) The name of the load balancer. Must be unique within your account, max 32 characters, alphanumeric and hyphens only. This name will be used in DNS records and AWS resource names, so choose something meaningful and compliant with DNS naming conventions.
	// The name of the load balancer. Must be unique within your account, max 32 characters, alphanumeric and hyphens only. This name will be used in DNS records and AWS resource names, so choose something meaningful and compliant with DNS naming conventions.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// 6 characters long. Conflicts with the name attribute - you can only use one or the other.
	// Creates a unique name beginning with the specified prefix. The prefix must be 1-6 characters long. Conflicts with the `name` attribute - you can only use one or the other.
	// +kubebuilder:validation:Optional
	NamePrefix *string `json:"namePrefix,omitempty" tf:"name_prefix,omitempty"`

	// ddd,hh24:mm-hh24:mm where:
	// Specifies a time window during which load balancer node forced replacement should preferably occur. An empty string is a valid value. The format is `ddd-ddd,hh24:mm-hh24:mm` where:
	//
	// * `ddd-ddd` represents a day range (e.g., `mon-fri` for Monday to Friday)
	// * `hh24:mm-hh24:mm` represents a time range in 24-hour format in UTC (e.g., `01:00-03:00` for 1 AM to 3 AM UTC)
	//
	// **Important:** All times are in UTC. The day of the week refers to the start time of the window. For time ranges that cross midnight, the window will finish on the next day.
	//
	// Examples:
	// * `mon-wed,02:00-04:00` - Monday through Wednesday, between 2 AM and 4 AM UTC
	// * `mon-fri,23:00-02:00` - Monday through Friday, starting at 11 PM UTC each day and ending at 2 AM UTC the following day. The last window starts at 11 PM UTC Friday and ends at 2 AM UTC Saturday
	//
	// When updates to the load balancer nodes are available, newly started instances always use the newest version, and older versions are progressively phased out as scale-in events occur. Additionally, any remaining instances running out-of-date versions will be automatically replaced during the specified maintenance window.
	//
	// Valid values for days are:
	//
	// * `mon` - Monday
	// * `tue` - Tuesday
	// * `wed` - Wednesday
	// * `thu` - Thursday
	// * `fri` - Friday
	// * `sat` - Saturday
	// * `sun` - Sunday
	//
	// **Note:** Urgent updates may be applied outside of the preferred maintenance window and without notice. `connection_draining_timeout` is always respected.
	//
	// If unspecified, non-urgent forced replacements will occur at night in the region.
	// +kubebuilder:validation:Optional
	PreferredMaintenanceWindow *string `json:"preferredMaintenanceWindow,omitempty" tf:"preferred_maintenance_window,omitempty"`

	// (Boolean) If true, the load balancer preserves the original Host header value in requests forwarded to targets. This is useful when your backend application needs to know the original hostname requested by the client, for example with virtual hosting or when generating absolute URLs.
	// If true, the load balancer preserves the original Host header value in requests forwarded to targets. This is useful when your backend application needs to know the original hostname requested by the client, for example with virtual hosting or when generating absolute URLs.
	// +kubebuilder:validation:Optional
	PreserveHostHeader *bool `json:"preserveHostHeader,omitempty" tf:"preserve_host_header,omitempty"`

	// (Set of String) List of security group IDs to assign to the load balancer. The security groups must allow inbound traffic on the listener ports and health check ports. They should also allow outbound traffic to your target instances or IP addresses, and the HLB control plane.
	// List of security group IDs to assign to the load balancer. The security groups must allow inbound traffic on the listener ports and health check ports. They should also allow outbound traffic to your target instances or IP addresses, and the HLB control plane.
	// +kubebuilder:validation:Optional
	// +listType=set
	SecurityGroups []*string `json:"securityGroups,omitempty" tf:"security_groups,omitempty"`

	// facing load balancers, these must be public subnets.
	// List of subnet IDs to attach to the load balancer. The subnets must be in at least two different Availability Zones for high availability. For internal load balancers, these must be private subnets. For internet-facing load balancers, these must be public subnets.
	// +kubebuilder:validation:Optional
	// +listType=set
	Subnets []*string `json:"subnets,omitempty" tf:"subnets,omitempty"`

	// value pairs that help you organize and categorize your resources. Common uses include:
	// A map of tags to assign to the load balancer and related resources. Tags are key-value pairs that help you organize and categorize your resources. Common uses include:
	//
	// * Environment identification (e.g., `environment = "production"`)
	// * Cost allocation (e.g., `project = "mobile-app"`)
	// * Security/compliance labeling
	// * Automation and operations management
	// A maximum of 5 tags can be assigned (AWS Marketplace limitation).
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Forwarded-For header. Valid values:
	// Controls how the load balancer handles the X-Forwarded-For header. Valid values:
	//
	// * `append` (default) - Appends the client IP to any existing X-Forwarded-For header
	// * `preserve` - Keeps the original X-Forwarded-For header unchanged
	// * `remove` - Removes any existing X-Forwarded-For header
	//
	// This header is important for identifying the original client IP address when requests pass through the load balancer.
	// +kubebuilder:validation:Optional
	XffHeaderProcessingMode *string `json:"xffHeaderProcessingMode,omitempty" tf:"xff_header_processing_mode,omitempty"`

	// (String) The ID of the zone
	// The ID of the zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// (String) The name of the zone
	// The name of the zone
	// +kubebuilder:validation:Optional
	ZoneName *string `json:"zoneName,omitempty" tf:"zone_name,omitempty"`
}

// HostedLoadBalancerSpec defines the desired state of HostedLoadBalancer
type HostedLoadBalancerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     HostedLoadBalancerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider HostedLoadBalancerInitParameters `json:"initProvider,omitempty"`
}

// HostedLoadBalancerStatus defines the observed state of HostedLoadBalancer.
type HostedLoadBalancerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        HostedLoadBalancerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// HostedLoadBalancer is the Schema for the HostedLoadBalancers API. Manages a Hero Load Balancer (HLB) resource. HLB is a managed load balancer service that distributes incoming application traffic across multiple targets, such as EC2 instances, in multiple Availability Zones. This resource allows you to create and manage load balancers with features like: HTTP/2 supportAccess loggingCross-zone load balancingCustom launch configurationsFlexible IP address types For detailed documentation and examples, see the HLB Provider Documentation ../index.md.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,zonehero}
type HostedLoadBalancer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.subnets) || (has(self.initProvider) && has(self.initProvider.subnets))",message="spec.forProvider.subnets is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zoneId) || (has(self.initProvider) && has(self.initProvider.zoneId))",message="spec.forProvider.zoneId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zoneName) || (has(self.initProvider) && has(self.initProvider.zoneName))",message="spec.forProvider.zoneName is a required parameter"
	Spec   HostedLoadBalancerSpec   `json:"spec"`
	Status HostedLoadBalancerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HostedLoadBalancerList contains a list of HostedLoadBalancers
type HostedLoadBalancerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []HostedLoadBalancer `json:"items"`
}

// Repository type metadata.
var (
	HostedLoadBalancer_Kind             = "HostedLoadBalancer"
	HostedLoadBalancer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: HostedLoadBalancer_Kind}.String()
	HostedLoadBalancer_KindAPIVersion   = HostedLoadBalancer_Kind + "." + CRDGroupVersion.String()
	HostedLoadBalancer_GroupVersionKind = CRDGroupVersion.WithKind(HostedLoadBalancer_Kind)
)

func init() {
	SchemeBuilder.Register(&HostedLoadBalancer{}, &HostedLoadBalancerList{})
}
