apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: zonehero-creds
type: Opaque
data:
  # credentials: BASE64ENCODED_PROVIDER_CREDS
---
apiVersion: zonehero.footprintit.net/v1beta1
kind: ProviderConfig
metadata:
  name: zonehero-provider
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: zonehero-creds
      key: credentials
